# DB configs.
# Here is a place for the common parts of these configs. 
# You can set the rest of these configs like usernames, passwords, hosts as env vars 
#   (config/.env or docker compose files or just setup env vars).
# DSN -> driver, creds, host, username, passwd, etc.
# Do not use multiple '_' characters consecutively in DSN name.
---
alpha:  # virtual db name (DSN)
  driver: sqlite
  database: alpha.db
  domain: dev
bravo:
  driver: sqlite
  database: bravo.db
  domain: dev
  password:
# one_pg:
#   driver: 'pg'
#   database: 'one'
#   domain: 'dev'
#   host: 'localhost'
#   username: 'username'
#   password: '***'
# one_mysql:
#   disabled: 1
#   driver: 'mysql'
#   database: 'one'
#   domain: 'dev'
#   host: 'localhost'
#   username: 'username'
#   password: '***'
#   post_connect_sql:
#     - 'SET NAMES utf8'
#   mysql_enable_utf8: 1
#   mysql_auto_reconnect: 1
