---
hypnotoad:
  listen:
    - 'http://*:8080'

app_secret_passphrase:
  - 'My very secret old passphrase.' 
  - 'My very secret new passphrase.' 

# Automatic pluralize each route except for routes with alt_route field.
route_pluralization: true

# Common route prefix for all routes.
route_prefix: /api