# This kind of config should be fully stored in the version control system without being overwritten by any env var.
# If you want to turn off some route you can just comment it out.
---
# App::Controller::REST::V1::Foo
- package_name: V1::Foo
  # alt_route is optional. If you want to use a different route than the one implied by the package name.
  # Lack of automatic pluralization.
  alt_route: /api/v1/alt_foo 
  actions:
    - list
    - get
- package_name: V1::Bar
  actions:
    - list
    - get
    - add
    - update
    - delete
    - patch  #TODO
    # /api/v1/bars/custom_action1/:id/:name
    - action: custom_action1
      method: POST
      placeholders:  # the order is important.
        - id
        - name
    # /api/v1/bars/custom_action2
    - action: custom_action2
      method: POST
- package_name: V2::Product
  actions:
    - list
    - get
    - add
    - update
- package_name: V2::Category
  actions:
    - list
- package_name: V2::Post
  actions:
    - list
    - get
    - add
    - update
    - delete
