# This kind of config should be fully stored in the version control system without being overwritten by any env var.
# If you want to turn off some route you can just comment it out.
---
# App::Controller::REST::V1::Foo based on SQLite.
- package_name: V1::Foo
  # alt_route is optional. If you want to use a different route than the one implied by the package name.
  # Lack of automatic pluralization.
  alt_route: /api/v1/alt_foo 
  actions: [list, get]
# Based on SQLite.
- package_name: V1::Bar
  actions:
    - list
    - get
    - add
    - update
    - delete
    - patch
    # /api/v1/bars/custom_action1/:id/:name
    # Watch out for collision of GET requet with :id (get action) and GET request with custom action.
    # In this case you must use the non-colliding method: POST.
    - action: custom_action1
      method: POST
      placeholders:  # the order is important.
        - id
        - name
    # /api/v1/bars/custom_action2
    - action: custom_action2
      method: POST
# Based on Redis.
- package_name: V1::Baz
  actions: [list, get, add, update, delete]
# Based on PostgreSQL.
- package_name: V1::Fruit
  actions: [list, get, add, update, delete]
# Based on gateway to https://dummyjson.com.
- package_name: V2::Product
  actions: [list, get, add, update]
# Based on gateway to https://dummyjson.com.
- package_name: V2::Category
  actions: [list]
# Based on gateway to https://jsonplaceholder.typicode.com.
- package_name: V2::Post
  actions: [list, get, add, update, delete]
